name: Code checks

on: [pull_request]

jobs:
  job1:
    name: linting and unit testing
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8 and Pytest
      run: |
        python -m pip install flake8
        python -m pip install pytest
    - name: Run linting tests
      run: | 
        flake8 src/model/
    - name: Run unit tests
      run: |
        pytest tests



